<?php

use Magento\Framework\App\ObjectManager;

?>
<div id="pwr-snippets">
	<!-- start_product_section_review_snippet_section -->
	<div id="pr-reviewsnippet" style="<?= $this->getProductPageReviewSnippet() ? '' : 'display: none;' ?>"></div>
	<!-- end_product_section_review_snippet_section -->

	<!-- start_product_question_snippet_section -->
	<div id="pr-questionsnippet" style="<?= $this->getProductPageQuestionSnippet() ? '' : 'display: none;' ?>"></div>
	<!-- end_product_question_snippet_section -->
</div>
<?php
$product = $this->getCurrentProduct();

$productType = $product->getTypeId();

$variants = $usedVariants = [];

// If we are having more than 1 variant
if ($productType == 'configurable') {
    $productCollection = $product->getTypeInstance()->getUsedProductCollection($product)->addAttributeToSelect('*');
    foreach ($productCollection as $productVariant) {
        if (in_array($productVariant->getData('page_id_variant'), $usedVariants)) {
            continue;
        }
        $item = array(
            'name' => $productVariant->getName(),
            'description' => $productVariant->getName(),
            'page_id_variant' => $productVariant->getData('page_id_variant'),
            'upc' => $productVariant->getData('pr_ean'),
            'price' => $productVariant->getPrice()
        );
        $variants[] = $item;
        $usedVariants[] = $productVariant->getData('page_id_variant');
    }
    $variants = array_values($variants);
}
?>

<?php
$productImageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_page_image_large')
    ->setImageFile($product->getFile())->getUrl();
?>

<?php
$objectManager = ObjectManager::getInstance();

$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');

$categoryIds = $product->getCategoryIds();

$categories = $categoryCollection->create()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('entity_id', $categoryIds);

$firstCategory = '';

# Per requirement we only take the first available category
foreach ($categories as $category) {
    $firstCategory = $category->getName();

    if ($firstCategory != '') {
        break;
    }
}
?>

<!-- start_review_render_code_js_section -->
<script>
    require(['jquery', 'jquery/ui'], function ($) {
        $("#pr-reviewdisplay").ready(function() {

        var components = {
            ReviewSnippet: 'pr-reviewsnippet',
            QuestionSnippet: 'pr-questionsnippet',
            QuestionDisplay: 'pr-questiondisplay'
        };

        if ($('#pr-reviewdisplay').length > 0) {
            components.ReviewDisplay = 'pr-reviewdisplay';
        }


        POWERREVIEWS.display.render({
            api_key: "<?= trim($this->getApiKey()) ?>",
            locale: "<?= trim($this->getLocale()) ?>",
            merchant_group_id: "<?= trim($this->getMerchantGroupId()) ?>",
            merchant_id: "<?= trim($this->getMerchantId()) ?>",
            page_id: "<?= trim(urlencode($this->getCurrentProduct()->getData('page_id'))) ?>",
            review_wrapper_url: "<?= $this->getBaseUrl()?>write-a-review/?pr_page_id=<?= trim(urlencode($this->getCurrentProduct()->getData('page_id')))?><?=$this->getCurrentProduct()->getData('page_id_variant') ? '&page_id_variant=' . trim(urlencode($this->getCurrentProduct()->getData('page_id_variant'))) : ''?>",
            on_read_reviews_click: function () {
                var reviewdisplay = $("#reviewdisplay\\.tab");
                $('#tab-label-reviewdisplay\\.tab-title').click();
                reviewdisplay.show();
                setTimeout(function () {
                    reviewdisplay[0].scrollIntoView(true);
                    document.body.scrollTop -= 100;
                }, 0);
            },
            on_view_answers_click: function () {
                var questiondisplay = $("#questiondisplay\\.tab");
                $('#tab-label-questiondisplay\\.tab-title').click();
                questiondisplay.show();
                setTimeout(function () {
                    questiondisplay[0].scrollIntoView(true);
                    document.body.scrollTop -= 100;
                }, 0);
            },
            product: {
                name: "<?= addslashes(str_replace(array("\n", "\r"), ' ', strip_tags($this->getCurrentProduct()->getName()))) ?>",
                url: "<?= $this->getCurrentProduct()->getProductUrl() ?>",
                image_url: "<?= $productImageUrl ?>",
                description: "<?= addslashes(str_replace(array("\n", "\r"), ' ', strip_tags($this->getCurrentProduct()->getDescription()))) ?>",
                category_name: "<?= $firstCategory != '' ? $firstCategory : 'default' ?>",
                upc: "<?= $product->getData('pr_ean') ?>",
                brand_name: "<?= $product->getData('brand_name')?>",
                manufacturer_id: "<?= $product->getData('pr_mpn')?>",
                price: "<?= $this->getCurrentProduct()->getPrice() ?>",
                <?php if(!empty($variants)) : ?>
                variants: <?= json_encode($variants) ?>,
                <?php endif; ?>
                in_stock: "<?= $this->getCurrentProduct()->isAvailable() ?>",
            },
            components: components
        });
        });
    });
</script>
<!-- end_review_render_code_js_section -->
