<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_grid_content_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>

<?php if ($exist):?>
    <div class="product-slider <?php /* @escapeNotVerified */ echo $type; ?>">
        <div class="product-slider__title"><?php /* @escapeNotVerified */ echo $title; ?></div>
        <div class="owl-carousel wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="item">
                    <div class="small-product-item">
                        <!-- image -->
                        <div class="small-product-item-img">
                            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                        </div>

                        <!-- info -->
                        <div class="small-product-item-info">
                            <div class="small-product-item-info__title">
                                <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                    <?php echo $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </div>
                            <div class="small-product-item-info-price">
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            </div>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <div class="field choice related">
                                        <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                        <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($showCart): ?>
                                <div class="actions-primary">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                            <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary"
                                                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_item->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

            <?php endforeach ?>
            </div>
        </div>
        <script type="text/javascript">
            require(['jquery'], function($){
                $(document).ready(function ($) {
                    $('.product-slider.<?php /* @escapeNotVerified */ echo $type; ?> > .owl-carousel').owlCarousel({
                        margin: 10,
                        loop: true,
                        nav: true,
                        navText: ['<i class="icon-left"/>','<i class="icon-right"/>'],
                        dots: false,
                        autoplay: true,
                        autoplayHoverPause: true,
                        responsive: {
                            0:{
                                items: 1
                            },
                            767:{
                                items: 3
                            },
                            1100:{
                                items: 4
                            }
                        }
                    });
                });
            });
        </script>
<?php endif;?>
