<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$stripSelection = $product->getConfigureMode() ? true : true;
$options = $block->decorateArray($block->getOptions($stripSelection));
?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }
</script>
        <fieldset class="fieldset fieldset-bundle-options">
           <!-- <legend id="customizeTitle" class="legend title">
                <span><?= /* @escapeNotVerified */ __('Customize %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></span>
            </legend><br /> JOEL REMOVED TITLE -->
            <div class='some-container'>
                <div class='row'>
                    <div class='left-column'>
                        <?php foreach ($options as $option): ?>
                            <?php if (!$option->getSelections()): ?>
                                <?php continue; ?>
                            <?php endif; ?>
                            <?= $block->getOptionHtml($option) ?>
                        <?php endforeach; ?>
                    </div>
                    <div class='right-column'>
                        <div class="media-wrapper">
                            <?= $block->getChildHtml('product.info.media') ?>
                        </div>
                        <div>
                            <?= $block->getChildHtml('bundle.summary') ?>  
                        </div>
                        <div>
                            <?= $block->getChildHtml('product.info.overview') ?>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?= /* @escapeNotVerified */ __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
