<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Helper\Output;
use Magento\Catalog\Model\Product;
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block ListProduct
 * @var $_helper Output
 * @var $_reviewHelper \PowerReviews\ReviewDisplay\Helper\Data
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_reviewHelper = $this->helper('PowerReviews\ReviewDisplay\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
	<div class="message info empty">
		<div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
	</div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	<div class="products wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
		<div class="category-product-list products list items product-items">
            <?php /** @var $_product Product */ ?>
            <?php foreach ($_productCollection

            as $_product): ?>

			<div class="catefory-product-item">
				<div class="product-item product-item-info">

					<!-- product image -->
					<div class="product-item-img">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
						<a href="<?php /* @escapeNotVerified */
                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
						</a>
					</div>

					<div class="product details product-item-details product-item-information">

                        <?php if ($viewMode == 'list'): ?>
						<div class="product-item-center-col">
                            <?php endif; ?>
							<!-- product title -->
							<div class="product-item-information-title">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</div>

							<!-- product reviews summery -->
                            <?php if (!$_reviewHelper->getEnable()): ?>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php endif; ?>
							<!-- product details -->
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <?php if ($showDescription): ?>
								<div class="product-item-information-description">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									<a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                    echo $_productNameStripped ?>"
									   class="action more"><?php /* @escapeNotVerified */
                                        echo __('Learn More') ?></a>
								</div>
                            <?php endif; ?>

                            <?php if ($viewMode == 'list'): ?>
						</div>
                    <?php endif; ?>

                        <?php if ($viewMode == 'list'): ?>
						<div class="product-item-right-col">
                            <?php endif; ?>
							<!-- product price -->
							<div class="product-item-information-price">
                                <?php /* @escapeNotVerified */
                                echo $block->getProductPrice($_product) ?>
							</div>

                            <?php if ($viewMode == 'grid'): ?>
						</div>
                    <?php endif; ?>
						<!-- add to cart -->
						<div class="product-item-add2cart">
							<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                    echo $postParams['action']; ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                        echo $postParams['data']['product']; ?>">
										<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                                        echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
										<input type="hidden" name="redirect_to_checkout" value="0"><?php echo $block->getBlockHtml('formkey') ?>
										<button type="submit"
										        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
										        class="action tocart primary">
											<span><?php /* @escapeNotVerified */
                                                echo __('Add to Cart') ?></span>
										</button>
										<a href="javascript:void(0)" class="action checkout quick-order primary"><span><?php /* @escapeNotVerified */
                                                echo __('Add to Cart and Checkout') ?></span></a>
									</form>
                                <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */
                                                echo __('In stock') ?></span></div>
                                    <?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
							</div>
						</div>
                        <?php if ($viewMode == 'list'): ?>
					</div>
				</div>
                <?php endif; ?>
			</div>
		</div>
    <?php endforeach; ?>
	</div>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
		<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

		</script>
    <?php endif; ?>
	<script>
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            $('a.checkout').on('click', function () {
                $(this).closest('form[data-role="tocart-form"]').find('input[name="redirect_to_checkout"]').val('1');
                $(this).closest('form[data-role="tocart-form"]').submit();
            });
            $('.actions-primary button[type="submit"]').on('click', function () {
                $(this).closest('form[data-role="tocart-form"]').find('input[name="redirect_to_checkout"]').val('0');
            });
        });
	</script>
<?php endif; ?>
